<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php
/**
 * Product carousel widget template
 *
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->count())): 
        
    ?>
    <?php
    $type = 'widget-product-carousel';

    $image = 'new_products_content_widget_grid';
    $_productCollection = $block->getProductCollection();
    $_productCollection->addAttributeToSelect('*');
    $_productCollection->addMediaGalleryData(); 
    $items = $_productCollection->getItems();
    
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>

    <ol class="product-items <?= /* @noEscape */ $type ?>">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item) { ?>
            <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
            <div class="product-item-info">
                <?php
                $imageHelper = $this->helper(\Magento\Catalog\Helper\Image::class);
                $imageUrl = $imageHelper
                    ->init($_item, $image)
                    ->constrainOnly(true)
                    ->keepAspectRatio(true)
                    ->keepFrame(false)
                    ->resize(800, 800)
                    ->getUrl();

                $galleryImages = $_item->getMediaGalleryImages();
                $hoverImageUrl = null;
                if ($galleryImages && count($galleryImages) > 1) {
                    $galleryItems = array_values($galleryImages->getItems());
                    if (isset($galleryItems[1])) {
                        $hoverImage = $galleryItems[1];
                        $hoverImageUrl = $imageHelper
                            ->init($_item, $image)
                            ->setImageFile($hoverImage->getFile())
                            ->constrainOnly(true)
                            ->keepAspectRatio(true)
                            ->keepFrame(false)
                            ->resize(800, 800)
                            ->getUrl();
                    }
                }
                ?>
                <div class="bv24-hover-image">
                    <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo bv24-hover-image" tabindex="-1">
                        <img src="<?= $imageUrl ?>" alt="<?= $_item->getName() ?>" class="bv24-main-image" />
                        <?php if ($hoverImageUrl) { ?>
                            <img src="<?= $hoverImageUrl ?>" alt="<?= $_item->getName() ?>" class="bv24-hover-img" />
                        <?php } ?>
                    </a>

                     <div data-role="add-to-links" class="bv24-addtolinks">
                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                    <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                <?php endif; ?>
                            </div>
                </div>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <a title="<?= $escaper->escapeHtml($_item->getName()) ?>"
                           href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                           class="product-item-link">
                            <?= $escaper->escapeHtml($_item->getName()) ?>
                        </a>
                    </strong>
                    <?php if ($templateType) { ?>
                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                    <?php } ?>

                    <?= $block->getProductPriceHtml($_item, $type) ?>

                    <?= $block->getProductDetailsHtml($_item) ?>

                    <?php if ($showWishlist || $showCompare || $showCart) { ?>
                        <div class="product-item-inner d-none">
                            <div class="product-item-actions">
                                <?php if ($showCart) { ?>
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()) { ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($_item->getSku()) ?>" action="<?= $escaper->escapeUrl($postParams['action']) ?>" method="post">
                                                <?php foreach ($postParams['data']['options'] as $optionItem) { ?>
                                                    <input type="hidden"
                                                           name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                           value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                                <?php } ?>
                                                <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                            <script type="text/x-magento-init">
                                            {
                                                "[data-role=tocart-form], .form.map.checkout": {
                                                    "catalogAddToCart": {
                                                        "product_sku": "<?= $escaper->escapeJs($_item->getSku()); ?>"
                                                    }
                                                }
                                            }
                                            </script>
                                        <?php } else { ?>
                                            <?php if ($_item->getIsSalable()) { ?>
                                                <div class="stock available"><span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                            <?php } else { ?>
                                                <div class="stock unavailable"><span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php } ?>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                <?php if ($showWishlist || $showCompare) { ?>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) { ?>
                                            <a href="#"
                                               data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                <span><?= $escaper->escapeHtml(__('Add to Wish List')) ?></span>
                                            </a>
                                        <?php } ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare) { ?>
                                            <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                            <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                <span><?= $escaper->escapeHtml(__('Add to Compare')) ?></span>
                                            </a>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
        <?php } ?>
    </ol>
<?php endif; ?>
