<div class="usp-swiper-wrapper">
<div class="usp-swiper">
    <div class="swiper-wrapper">
        <div class="swiper-slide"><i class="ri-layout-masonry-line" style="color: #fff; font-size: 2rem; padding-right: 5px"></i> 5 kostenlose Muster</div>
        <div class="swiper-slide"><i class="ri-discount-percent-line" style="color: #fff; font-size: 2rem; padding-right: 5px"></i> Bestpreis Garantie</div>
        <div class="swiper-slide"><i class="ri-customer-service-2-line" style="color: #fff; font-size: 2rem; padding-right: 5px"></i> persönliche Beratung</div>
        <div class="swiper-slide"><i class="ri-truck-line" style="color: #fff; font-size: 2rem; padding-right: 5px"></i> kostenfreier Versand in DE</div>
    </div>
</div>
</div>
